# Operations Over 1-D Arrays

<h2 style = \"color : Brown\"> Case Study - Cricket Tournament </h2>


A panel wants to select players for an upcoming league match based on their fitness. Players from all significant cricket clubs have participated in a practice match, and their data is collected. Let us now explore NumPy features using the player's data.

### Example -1

**Heights of the players is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it ?**

In [69]:
heights = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]

In [70]:
import numpy as np

In [3]:
heights_in = np.array(heights)

In [4]:
heights_in

array([74, 74, 72, ..., 75, 75, 73])

In [5]:
type(heights_in)

numpy.ndarray

### Example-2

**Count the number of participations**

In [6]:
len(heights_in)

1015

In [7]:
heights_in.size

1015

In [8]:
# Mostly used for the second D but due to having 1 D, we are using shape
heights_in.shape

(1015,)

### Example - 3

**Conver the heights from inches to meters**

In [9]:
heights_in_m = heights_in * 0.0254

In [10]:
heights_in_m

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

### Example - 4

A list of weights (in lbs) of the plyaers is provided. Convert it to kg and calculate BMI

In [11]:
weights_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

In [12]:
# Convert it to kg to lbs

weights_kg = np.array(weights_lb) * 0.453592

weights_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [13]:
# Calculate the BMI

bmi = weights_kg /(heights_in_m **2)
bmi

array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

#### We can able to do this in single line without using any looping So, thats the main reson behind numPy

### Sub-Setting Arryas

In [14]:
bmi[0]

23.11037638875862

In [16]:
for i in bmi:
    print(int(round(i)),end=" ")

23 28 28 28 25 26 31 28 28 25 25 24 24 21 27 27 25 23 25 26 25 30 24 24 27 28 24 25 24 24 23 24 25 26 31 30 28 27 24 26 26 28 24 26 26 27 25 26 27 28 26 25 26 27 24 26 28 24 24 28 26 34 24 26 23 28 24 28 26 29 28 26 26 27 24 28 24 26 25 25 28 28 27 24 26 27 35 28 23 21 26 23 28 26 25 28 28 22 25 25 29 30 24 29 27 24 22 26 27 26 29 24 23 30 25 28 27 26 26 28 24 23 24 25 24 26 24 24 30 24 28 26 25 26 27 24 28 29 26 25 22 24 24 24 25 22 26 28 27 26 27 25 24 23 33 23 23 24 28 21 25 24 27 28 26 30 29 27 24 27 26 26 26 28 26 25 24 24 25 24 27 28 28 30 27 28 30 23 28 24 26 24 29 27 24 29 24 24 23 24 25 26 26 22 24 26 26 28 26 27 27 23 24 26 24 29 30 24 27 24 29 27 26 22 27 25 26 26 28 35 24 27 29 26 27 22 32 26 27 30 24 27 27 27 23 24 27 29 29 24 24 26 28 25 27 28 24 26 28 26 29 26 25 29 29 26 25 24 26 26 26 21 27 27 26 28 22 27 27 20 31 26 26 25 26 26 25 27 28 24 24 29 23 26 24 26 28 24 26 28 25 25 25 25 27 24 26 27 24 27 26 24 25 22 28 23 26 28 26 24 23 21 28 24 26 23 26 26 24 22 29 27 26 29 27 24 26 24 28 26 28 25 24 25 24 24 22 26 24 24 30 27 27 26 25 24 26 20 25 28 26 26 25 26 24 22 28 23 26 24 28 24 28 24 27 25 27 24 21 25 26 31 28 30 24 27 22 23 30 25 25 21 28 29 24 23 23 27 30 24 27 26 26 27 26 25 27 23 29 24 27 25 24 25 28 27 26 23 30 24 25 27 28 27 27 26 29 24 23 31 30 22 24 27 24 27 22 24 28 27 28 28 26 24 25 24 27 26 26 21 29 27 26 28 24 28 29 23 32 24 27 26 28 23 28 27 23 25 31 31 26 28 25 23 22 24 26 26 24 27 27 24 28 24 25 24 22 24 27 28 26 23 26 29 27 26 26 25 24 21 32 24 28 23 30 27 31 26 26 23 29 24 24 28 26 24 28 30 28 27 28 24 24 23 23 25 23 23 24 28 28 30 25 27 26 26 28 27 28 26 26 24 27 27 29 27 28 25 25 25 26 23 25 30 27 27 31 26 24 21 29 30 33 25 24 24 29 31 31 24 29 28 23 28 23 24 27 26 26 24 25 26 24 24 28 28 24 24 27 29 24 26 25 25 24 30 31 22 29 29 23 25 28 26 26 25 28 26 27 27 27 26 24 30 24 28 26 29 26 25 26 26 23 26 27 24 27 26 27 24 24 28 28 27 26 29 28 26 27 26 26 25 27 26 24 26 25 24 24 22 29 25 27 27 25 27 28 26 20 24 27 24 27 23 26 21 25 27 25 27 26 27 29 25 29 28 25 26 22 27 26 27 26 25 24 27 25 32 21 25 25 27 28 28 26 23 21 24 29 29 27 26 27 26 22 26 25 27 26 26 25 26 29 25 25 26 26 25 26 23 27 31 28 25 28 26 26 22 24 28 27 25 31 24 25 25 26 28 28 29 23 26 19 26 28 31 25 26 28 25 28 24 24 26 28 27 32 24 24 26 24 27 30 24 25 33 27 29 27 29 23 26 22 26 27 28 28 28 23 26 28 28 24 27 25 26 25 23 25 24 28 27 22 21 24 29 24 30 27 25 23 24 22 30 27 26 21 22 22 23 27 27 29 28 25 35 26 25 25 23 26 26 27 31 28 26 25 23 26 27 25 28 26 23 27 24 29 28 26 30 26 24 24 26 29 25 27 27 28 27 25 25 29 32 25 30 28 24 26 29 24 26 26 25 24 22 25 26 28 29 31 30 24 27 23 26 24 25 26 24 28 28 23 23 28 24 26 23 25 26 31 25 27 24 24 27 25 24 27 21 29 26 23 23 24 23 21 29 25 27 31 24 26 27 28 27 22 27 29 26 26 28 26 26 26 26 26 24 27 27 26 27 27 29 27 26 28 24 26 27 27 29 26 30 28 27 26 23 23 31 30 26 28 30 24 26 25 27 26 26 26 25 27 29 24 27 21 27 26 27 27 26 25 25 28 28 28 26 27 25 24 26 22 28 31 25 28 24 28 26 29 28 28 23 27 25 28 25 23 24 28 22 25 27 26 29 28 27 24 26 25 23 26 24 26

**Fetch the last Elements from the array**

In [17]:
int(round(bmi[-1]))

26

**Fetch the first 5 elemets from the array**

In [18]:
bmi[0:5]

array([23.11037639, 27.60406069, 28.48080465, 28.48080465, 24.80333518])

**Fetch the last 5 elemets from the array**

In [19]:
bmi[len(bmi)-5:]

array([25.06720044, 23.11037639, 25.62295933, 23.74810865, 25.72686361])

In [20]:
bmi[-5:]

array([25.06720044, 23.11037639, 25.62295933, 23.74810865, 25.72686361])

### Conditional Sub-Setting Array 
<I>**Count the number of participants who are underweight -bmi <21 </I>**

In [21]:
type(bmi)

numpy.ndarray

In [25]:
bmi < 21

array([False, False, False, ..., False, False, False])

In [42]:
(bmi [bmi<21])

array([20.54255679, 20.54255679, 20.69282047, 20.69282047, 20.34343189,
       20.34343189, 20.69282047, 20.15883472, 19.4984471 , 20.69282047,
       20.9205219 ])

In [37]:
underweight_plyaers = bmi [bmi<21]
underweight_plyaers.size

11

### NumPy Functions

**Find the largest BMI value**

In [43]:
max(bmi)

35.26194861031698

In [44]:
# NumPy has own function to caLCULATE than max

bmi.max()

35.26194861031698

In [45]:
bmi.min()

19.498447103560874

In [46]:
bmi.mean()

26.05684565448554

In [48]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[ : : -2])

[2, 5, 7, 4, 3, 1]

# Practice 1 Questions

In [49]:
array_1 = np.array([1, 5, 9, 12, 15, 7, 12, 9 ])

In [67]:
final_array = array_1[np.logical_and(array_1 >12, array_1<3)]
final_array

array([], dtype=int64)

In [68]:
list(final_array)

[]

In [57]:
.a

SyntaxError: invalid syntax (<ipython-input-57-4351eb581c1e>, line 1)